# Generated by Django 4.0 on 2021-12-22 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pen',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
