# Generated by Django 4.0 on 2021-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_pen_created_date_pen_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailsactivity',
            name='damagedEggsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='hatchedEggsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='newBabySnails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='newBreederStocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='newEggsCollected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='snailReshuffle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='totalMortalities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailscurrentinventory',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
    ]
