# Generated by Django 4.0 on 2021-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_eggsinventory_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsinventory',
            name='damagedEggsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggsinventory',
            name='hatchedEggsCount',
            field=models.IntegerField(default=0),
        ),
    ]
