# Generated by Django 4.0 on 2021-12-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_eggsinventory_damagedeggscount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailsactivity',
            name='hatchedEggsCount',
        ),
    ]
