# Generated by Django 4.0 on 2021-12-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_closingsnailsinventory_openingsnailsinventory_specie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snailsactivity',
            old_name='species',
            new_name='specieType',
        ),
        migrations.RemoveField(
            model_name='closingsnailsinventory',
            name='species',
        ),
        migrations.AddField(
            model_name='closingsnailsinventory',
            name='specieType',
            field=models.ForeignKey(default='AMO', on_delete=django.db.models.deletion.CASCADE, to='rest_api.specie', to_field='specie'),
        ),
        migrations.AddField(
            model_name='openingsnailsinventory',
            name='specieType',
            field=models.ForeignKey(default='AMO', on_delete=django.db.models.deletion.CASCADE, to='rest_api.specie', to_field='specie'),
        ),
        migrations.AddField(
            model_name='specie',
            name='specieDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
