# Generated by Django 4.0 on 2021-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_rename_species_snailsactivity_specietype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='specie',
            field=models.CharField(choices=[('AMO', 'AMO'), ('AMS', 'AMS'), ('AF', 'AF')], max_length=100, null=True, unique=True),
        ),
    ]
