# Generated by Django 4.0 on 2021-12-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_alter_specie_specie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningSnailsInventory',
        ),
    ]
