# Generated by Django 4.0 on 2021-12-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_delete_openingsnailsinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggsinventory',
            name='damagedEggsCount',
        ),
        migrations.RemoveField(
            model_name='eggsinventory',
            name='hatchedEggsCount',
        ),
        migrations.AddField(
            model_name='eggsinventory',
            name='specieType',
            field=models.ForeignKey(default='AMO', on_delete=django.db.models.deletion.CASCADE, to='rest_api.specie', to_field='specie'),
        ),
    ]
