# Generated by Django 4.0 on 2021-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_remove_eggsinventory_damagedeggscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsinventory',
            name='dateRecorded',
            field=models.DateTimeField(),
        ),
    ]
