# Generated by Django 4.0 on 2021-12-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_alter_eggsinventory_daterecorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggsinventory',
            old_name='dateRecorded',
            new_name='dateTimeRecorded',
        ),
    ]
