# Generated by Django 4.0 on 2021-12-24 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_rename_daterecorded_eggsinventory_datetimerecorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closingsnailsinventory',
            name='dateRecorded',
        ),
        migrations.RemoveField(
            model_name='snailsactivity',
            name='dateRecorded',
        ),
        migrations.AddField(
            model_name='closingsnailsinventory',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='closingsnailsinventory',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 12, 6, 4, 703725, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='snailsactivity',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 12, 6, 4, 704723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 12, 6, 4, 704723, tzinfo=utc)),
        ),
    ]
