# Generated by Django 4.0 on 2021-12-24 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_remove_closingsnailsinventory_daterecorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingsnailsinventory',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailsactivity',
            name='dateTimeRecorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
