# Generated by Django 4.0 on 2021-12-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_snailsactivity_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsinventory',
            name='specieType',
            field=models.ForeignKey(default='AMO', on_delete=django.db.models.deletion.CASCADE, related_name='specie_type', to='rest_api.specie', to_field='specie'),
        ),
    ]
