# Generated by Django 4.0 on 2021-12-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_alter_eggsinventory_specietype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='closingsnailsinventory',
            table='snails_inventory',
        ),
    ]
