# Generated by Django 4.0 on 2022-02-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_alter_eggsinventory_options_alter_pen_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='responsible',
        ),
    ]
