# Generated by Django 4.0 on 2022-02-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='responsible',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.CASCADE, to='rest_api.staff', to_field='name'),
        ),
    ]
