# Generated by Django 4.0 on 2022-04-05 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_snailsactivity_feedconsumptionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstransfer',
            name='specieType',
            field=models.ForeignKey(default='AMO', on_delete=django.db.models.deletion.CASCADE, to='rest_api.specie', to_field='specie'),
        ),
        migrations.CreateModel(
            name='EggsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeRecorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('newEggsCollected', models.IntegerField(default=0)),
                ('hatchedEggsCount', models.IntegerField(default=0)),
                ('damagedEggsCount', models.IntegerField(default=0)),
                ('comments', models.TextField(null=True)),
                ('penNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.pen')),
            ],
            options={
                'verbose_name_plural': 'Eggs Activities',
                'db_table': 'eggs_activities',
                'managed': True,
            },
        ),
    ]
