DELETE FROM closing_snails_inventory;
DELETE FROM pen_numbers;
DELETE FROM eggs_inventory;
DELETE FROM snails_species;
DELETE FROM snails_activities;

INSERT INTO snails_species (specie, specieDescription)
VALUES ('AMO', 'Archachatina Marginata Ovum'),
       ('AMS', 'Archachatina Marginata Saturalis'),
       ('AF', 'Achatina Fulica');

INSERT INTO pen_numbers (number, size, created_date, modified_date)
VALUES (0, 'Nursery Basket', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (1, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (2, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (3, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (4, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (5, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (6, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (7, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (8, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (9, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (10, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (11, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (12, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (13, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (14, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (15, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (16, '5 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (17, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (18, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (19, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (20, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (21, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (22, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (23, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (24, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (25, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (26, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (27, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (28, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (29, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (30, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (31, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (32, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (33, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (34, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (35, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (36, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (37, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (38, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (39, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (40, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (41, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (42, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (43, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (44, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (45, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (46, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (47, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (48, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (49, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (50, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (51, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (52, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (53, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (54, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (55, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (56, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (57, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (58, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (59, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (60, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (61, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (62, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (63, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (64, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (65, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (66, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (67, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (68, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (69, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (70, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (71, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (72, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (73, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (74, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (75, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (76, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (77, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (78, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (79, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (80, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (81, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (82, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (83, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (84, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (85, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (86, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (87, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (88, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (89, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (90, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (91, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (92, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (93, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (94, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (95, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (96, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (97, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (98, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (99, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (100, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (101, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (102, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (103, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (104, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (105, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (106, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (107, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (108, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (109, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (110, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (111, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (112, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (113, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (114, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (115, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (116, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (117, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (118, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (119, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (120, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (121, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (122, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (123, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (124, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (125, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (126, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (127, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (128, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (129, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (130, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (131, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (132, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (133, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (134, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (135, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (136, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (137, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (138, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (139, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (140, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (141, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (142, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (143, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (144, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (145, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (146, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (147, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (148, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (149, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (150, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (151, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (152, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (153, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (154, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (155, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (156, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (157, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (158, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (159, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day')),
       (160, '3 x 6 feet', DATETIME('now', '-2 day'), DATETIME('now', '-2 day'))
;

INSERT INTO eggs_inventory (dateTimeRecorded, totalCount, specieType_id, penNumber_id, comments)
VALUES (DATETIME('now', '-2 day'), 1075, 'AMO', 108, 'Actual eggs count at 23/12/2021');



INSERT INTO closing_snails_inventory (penNumber_id, specieType_id, dateTimeRecorded, totalCount)
VALUES
    (0, 'AMO', DATETIME('now', '-2 day'), 168),
    (1, 'AMO', DATETIME('now', '-2 day'), 0),
    (2, 'AMO', DATETIME('now', '-2 day'), 0),
    (3, 'AMO', DATETIME('now', '-2 day'), 0),
    (4, 'AMO', DATETIME('now', '-2 day'), 0),
    (5, 'AMO', DATETIME('now', '-2 day'), 0),
    (6, 'AMO', DATETIME('now', '-2 day'), 0),
    (7, 'AMO', DATETIME('now', '-2 day'), 0),
    (8, 'AMO', DATETIME('now', '-2 day'), 0),
    (9, 'AMO', DATETIME('now', '-2 day'), 0),
    (10, 'AMO', DATETIME('now', '-2 day'), 0),
    (11, 'AMO', DATETIME('now', '-2 day'), 0),
    (12, 'AMO', DATETIME('now', '-2 day'), 0),
    (13, 'AMO', DATETIME('now', '-2 day'), 0),
    (14, 'AMO', DATETIME('now', '-2 day'), 0),
    (15, 'AMO', DATETIME('now', '-2 day'), 0),
    (16, 'AMO', DATETIME('now', '-2 day'), 0),
    (17, 'AMO', DATETIME('now', '-2 day'), 0),
    (18, 'AMO', DATETIME('now', '-2 day'), 0),
    (19, 'AMO', DATETIME('now', '-2 day'), 0),
    (20, 'AMO', DATETIME('now', '-2 day'), 0),
    (21, 'AMO', DATETIME('now', '-2 day'), 0),
    (22, 'AMO', DATETIME('now', '-2 day'), 0),
    (23, 'AMO', DATETIME('now', '-2 day'), 0),
    (24, 'AMO', DATETIME('now', '-2 day'), 0),
    (25, 'AMO', DATETIME('now', '-2 day'), 0),
    (26, 'AMO', DATETIME('now', '-2 day'), 0),
    (27, 'AMO', DATETIME('now', '-2 day'), 0),
    (28, 'AMO', DATETIME('now', '-2 day'), 0),
    (29, 'AMO', DATETIME('now', '-2 day'), 0),
    (30, 'AMO', DATETIME('now', '-2 day'), 0),
    (31, 'AMO', DATETIME('now', '-2 day'), 0),
    (32, 'AMO', DATETIME('now', '-2 day'), 0),
    (33, 'AMO', DATETIME('now', '-2 day'), 0),
    (34, 'AMO', DATETIME('now', '-2 day'), 0),
    (35, 'AMO', DATETIME('now', '-2 day'), 0),
    (36, 'AMO', DATETIME('now', '-2 day'), 0),
    (37, 'AMO', DATETIME('now', '-2 day'), 0),
    (38, 'AMO', DATETIME('now', '-2 day'), 0),
    (39, 'AMO', DATETIME('now', '-2 day'), 0),
    (40, 'AMO', DATETIME('now', '-2 day'), 0),
    (41, 'AMO', DATETIME('now', '-2 day'), 0),
    (42, 'AMO', DATETIME('now', '-2 day'), 0),
    (43, 'AMO', DATETIME('now', '-2 day'), 0),
    (44, 'AMO', DATETIME('now', '-2 day'), 0),
    (45, 'AMO', DATETIME('now', '-2 day'), 0),
    (46, 'AMO', DATETIME('now', '-2 day'), 0),
    (47, 'AMO', DATETIME('now', '-2 day'), 0),
    (48, 'AMO', DATETIME('now', '-2 day'), 0),
    (49, 'AMO', DATETIME('now', '-2 day'), 0),
    (50, 'AMO', DATETIME('now', '-2 day'), 0),
    (51, 'AMO', DATETIME('now', '-2 day'), 0),
    (52, 'AMO', DATETIME('now', '-2 day'), 0),
    (53, 'AMO', DATETIME('now', '-2 day'), 0),
    (54, 'AMO', DATETIME('now', '-2 day'), 0),
    (55, 'AMO', DATETIME('now', '-2 day'), 0),
    (56, 'AMO', DATETIME('now', '-2 day'), 0),
    (57, 'AMO', DATETIME('now', '-2 day'), 0),
    (58, 'AMO', DATETIME('now', '-2 day'), 0),
    (59, 'AMO', DATETIME('now', '-2 day'), 0),
    (60, 'AMO', DATETIME('now', '-2 day'), 0),
    (61, 'AMO', DATETIME('now', '-2 day'), 0),
    (62, 'AMO', DATETIME('now', '-2 day'), 0),
    (63, 'AMO', DATETIME('now', '-2 day'), 0),
    (64, 'AMO', DATETIME('now', '-2 day'), 0),
    (65, 'AMO', DATETIME('now', '-2 day'), 0),
    (66, 'AMO', DATETIME('now', '-2 day'), 0),
    (67, 'AMO', DATETIME('now', '-2 day'), 0),
    (68, 'AMO', DATETIME('now', '-2 day'), 0),
    (69, 'AMO', DATETIME('now', '-2 day'), 0),
    (70, 'AMO', DATETIME('now', '-2 day'), 0),
    (71, 'AMO', DATETIME('now', '-2 day'), 0),
    (72, 'AMO', DATETIME('now', '-2 day'), 0),
    (73, 'AMO', DATETIME('now', '-2 day'), 0),
    (74, 'AMO', DATETIME('now', '-2 day'), 0),
    (75, 'AMO', DATETIME('now', '-2 day'), 0),
    (76, 'AMO', DATETIME('now', '-2 day'), 0),
    (77, 'AMO', DATETIME('now', '-2 day'), 0),
    (78, 'AMO', DATETIME('now', '-2 day'), 0),
    (79, 'AMO', DATETIME('now', '-2 day'), 0),
    (80, 'AMO', DATETIME('now', '-2 day'), 0),
    (81, 'AMO', DATETIME('now', '-2 day'), 0),
    (82, 'AMO', DATETIME('now', '-2 day'), 0),
    (83, 'AMO', DATETIME('now', '-2 day'), 0),
    (84, 'AMO', DATETIME('now', '-2 day'), 0),
    (85, 'AMO', DATETIME('now', '-2 day'), 0),
    (86, 'AMO', DATETIME('now', '-2 day'), 0),
    (87, 'AMO', DATETIME('now', '-2 day'), 0),
    (88, 'AMO', DATETIME('now', '-2 day'), 0),
    (89, 'AMO', DATETIME('now', '-2 day'), 0),
    (90, 'AMO', DATETIME('now', '-2 day'), 0),
    (91, 'AMO', DATETIME('now', '-2 day'), 0),
    (92, 'AMO', DATETIME('now', '-2 day'), 0),
    (93, 'AMO', DATETIME('now', '-2 day'), 0),
    (94, 'AMO', DATETIME('now', '-2 day'), 0),
    (95, 'AMO', DATETIME('now', '-2 day'), 0),
    (96, 'AMO', DATETIME('now', '-2 day'), 0),
    (97, 'AMO', DATETIME('now', '-2 day'), 0),
    (98, 'AMO', DATETIME('now', '-2 day'), 0),
    (99, 'AMO', DATETIME('now', '-2 day'), 95),
    (100, 'AMO', DATETIME('now', '-2 day'), 99),
    (101, 'AMO', DATETIME('now', '-2 day'), 0),
    (102, 'AMO', DATETIME('now', '-2 day'), 0),
    (103, 'AMO', DATETIME('now', '-2 day'), 0),
    (104, 'AMO', DATETIME('now', '-2 day'), 0),
    (105, 'AMO', DATETIME('now', '-2 day'), 0),
    (106, 'AMO', DATETIME('now', '-2 day'), 0),
    (107, 'AMO', DATETIME('now', '-2 day'), 0),
    (108, 'AMO', DATETIME('now', '-2 day'), 0),
    (109, 'AMO', DATETIME('now', '-2 day'), 0),
    (110, 'AMO', DATETIME('now', '-2 day'), 0),
    (111, 'AMO', DATETIME('now', '-2 day'), 0),
    (112, 'AMO', DATETIME('now', '-2 day'), 0),
    (113, 'AMO', DATETIME('now', '-2 day'), 0),
    (114, 'AMS', DATETIME('now', '-2 day'), 113),
    (115, 'AMS', DATETIME('now', '-2 day'), 99),
    (116, 'AMS', DATETIME('now', '-2 day'), 99),
    (117, 'AMS', DATETIME('now', '-2 day'), 100),
    (118, 'AMS', DATETIME('now', '-2 day'), 99),
    (119, 'AMO', DATETIME('now', '-2 day'), 100),
    (120, 'AMO', DATETIME('now', '-2 day'), 100),
    (121, 'AMO', DATETIME('now', '-2 day'), 99),
    (122, 'AMO', DATETIME('now', '-2 day'), 100),
    (123, 'AMO', DATETIME('now', '-2 day'), 100),
    (124, 'AMO', DATETIME('now', '-2 day'), 100),
    (125, 'AMO', DATETIME('now', '-2 day'), 99),
    (126, 'AMO', DATETIME('now', '-2 day'), 100),
    (127, 'AMO', DATETIME('now', '-2 day'), 100),
    (128, 'AMO', DATETIME('now', '-2 day'), 0),
    (129, 'AMO', DATETIME('now', '-2 day'), 0),
    (130, 'AMO', DATETIME('now', '-2 day'), 0),
    (131, 'AMO', DATETIME('now', '-2 day'), 89),
    (132, 'AMO', DATETIME('now', '-2 day'), 96),
    (133, 'AMO', DATETIME('now', '-2 day'), 98),
    (134, 'AMO', DATETIME('now', '-2 day'), 99),
    (135, 'AMO', DATETIME('now', '-2 day'), 100),
    (136, 'AMO', DATETIME('now', '-2 day'), 98),
    (137, 'AMO', DATETIME('now', '-2 day'), 100),
    (138, 'AMO', DATETIME('now', '-2 day'), 99),
    (139, 'AMO', DATETIME('now', '-2 day'), 96),
    (140, 'AMO', DATETIME('now', '-2 day'), 92),
    (141, 'AMO', DATETIME('now', '-2 day'), 95),
    (142, 'AMO', DATETIME('now', '-2 day'), 97),
    (143, 'AMO', DATETIME('now', '-2 day'), 109),
    (144, 'AMO', DATETIME('now', '-2 day'), 0),
    (145, 'AMO', DATETIME('now', '-2 day'), 0),
    (146, 'AMO', DATETIME('now', '-2 day'), 0),
    (147, 'AMO', DATETIME('now', '-2 day'), 99),
    (148, 'AMO', DATETIME('now', '-2 day'), 99),
    (149, 'AMO', DATETIME('now', '-2 day'), 99),
    (150, 'AMO', DATETIME('now', '-2 day'), 100),
    (151, 'AMO', DATETIME('now', '-2 day'), 100),
    (152, 'AMO', DATETIME('now', '-2 day'), 99),
    (153, 'AMO', DATETIME('now', '-2 day'), 100),
    (154, 'AMO', DATETIME('now', '-2 day'), 95),
    (155, 'AMO', DATETIME('now', '-2 day'), 97),
    (156, 'AMO', DATETIME('now', '-2 day'), 98),
    (157, 'AMO', DATETIME('now', '-2 day'), 95),
    (158, 'AMO', DATETIME('now', '-2 day'), 8),
    (159, 'AMO', DATETIME('now', '-2 day'), 0),
    (160, 'AMO', DATETIME('now', '-2 day'), 0);
